name: task2 trigger test

on:
  push:
    branches:
      - main

jobs:
  task2:
    runs-on: ubuntu-latest
    steps:
      - name: Task2 Trigger Test
        run: |
          echo "Jenkins Task-2 trigger test successful"
          exit 0

